---
train:
  params:
    batch_size: 64
    epoch: 100
    lr: 0.001
    decay: 0.1
    decay_step: 8000
    loss: MSELoss
  save:
    save_path: "/home/cyh/GazeBenchmark/exp/Implementation/Dilated-Net-rt"
    model_name: dilated
    step: 10
  data:
    image: "/home/cyh/GazeDataset20200519/Original/Rt-Gene"
    label: "/home/cyh/GazeDataset20200519/FaceBased/RT-Gene/Label/train"
  pretrains: "None"
test:
   load:
      begin_step: 10
      end_step: 100
      steps: 10
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Dilated-Net-rt"
      model_name: dilated
   data:
      image: "/home/cyh/GazeDataset20200519/Original/Rt-Gene"
      label: "/home/cyh/GazeDataset20200519/FaceBased/RT-Gene/Label-glasses/train"
reader: reader_rt
