---
train:
  params:
    batch_size: 64
    epoch: 100
    lr: 0.001
    decay: 0.1
    decay_step: 8000
    loss: MSELoss
  save:
    save_path: "/home/cyh/GazeBenchmark/exp/Implementation/Dilated-Net"
    model_name: DilatedNet
    step: 20
  data:
    image: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Image"
    label: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Label"
  pretrains: "None"
test:
   load:
      begin_step: 20
      end_step: 20
      steps: 20
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Dilated-Net"
      model_name: DilatedNet
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Image"
      label: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Label"
reader: reader_mpii
